const CoursesData = [
  {
    course_id: "1",
    name: "Computer - Web Development (HTML , CSS , JS etc)",
    img: "/assets/banner1.jpg",
    amount: "$840",
    instructor_name: "JIM BENNET",
    course_duration: "45 hrs",
  },
  {
    course_id: "2",
    name: "Computer - Mobile App Development ",
    img: "/assets/Courses/c5.jpg",
    amount: "$700",
    instructor_name: "SAANJ",
    course_duration: "28 hrs",
  },
  {
    course_id: "3",
    name: "Computer - Data Science",
    img: "/assets/Courses/c2.jpg",
    amount: "$800",
    instructor_name: "NIKO",
    course_duration: "29 hrs",
  },
  {
    course_id: "4",
    name: "Computer - Cybersecurity",
    img: "/assets/Courses/c7.jpg",
    amount: "$300",
    instructor_name: "ANKUR BAG",
    course_duration: "32 hrs",
  },
  {
    course_id: "5",
    name: "Creative Arts & Design - Graphic Design",
    img: "/assets/HOME 3.jpg",
    amount: "$160",
    instructor_name: "SAANJ",
    course_duration: "4 hrs",
  },
  {
    course_id: "5",
    name: "Creative Arts & Design - Photography",
    img: "/assets/COURSES4.jpg",
    amount: "$100",
    instructor_name: "Saanj",
    course_duration: "2hrs",
  },
  {
    course_id: "5",
    name: "Creative Arts & Design - Video Editing and Production",
    img: "/assets/COURSES4.jpg",
    amount: "$100",
    instructor_name: "Saanj",
    course_duration: "2hrs",
  },

  {
    course_id: "5",
    name: "Languages - ESL",
    img: "/assets/COURSES4.jpg",
    amount: "$100",
    instructor_name: "Saanj",
    course_duration: "2hrs",
  },
  {
    course_id: "5",
    name: "Languages - Sign Language",
    img: "/assets/COURSES4.jpg",
    amount: "$100",
    instructor_name: "Saanj",
    course_duration: "2hrs",
  },
  {
    course_id: "5",
    name: "Academic - STEM",
    img: "/assets/COURSES4.jpg",
    amount: "$100",
    instructor_name: "Saanj",
    course_duration: "2hrs",
  },
  {
    course_id: "5",
    name: "Academic - Mathematics",
    img: "/assets/COURSES4.jpg",
    amount: "$100",
    instructor_name: "Saanj",
    course_duration: "2hrs",
  },
  {
    course_id: "5",
    name: "Academic - Psychology",
    img: "/assets/COURSES4.jpg",
    amount: "$100",
    instructor_name: "Saanj",
    course_duration: "2hrs",
  },

  {
    course_id: "5",
    name: "SEO and Digital Marketing",
    img: "/assets/COURSES4.jpg",
    amount: "$100",
    instructor_name: "Saanj",
    course_duration: "2hrs",
  },
  {
    course_id: "5",
    name: "Blockchain and Cryptocurrency",
    img: "/assets/COURSES4.jpg",
    amount: "$100",
    instructor_name: "Saanj",
    course_duration: "2hrs",
  },
];

module.exports = CoursesData;
